# Generated by Django 2.2.1 on 2019-09-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190910_1641'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='per',
        ),
    ]
