# Generated by Django 2.2.1 on 2019-09-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190910_1643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='pres',
        ),
    ]
